### ISSUE TITLE
Background for code blocks is distracting

### ISSUE THREAD

**Issue by skurfer** [GwynethLlewelyn/Nord.novaextension#1]
Would you consider a different background color for code blocks? This is pretty hard to read, or even look at, in my opinion. 😬 (I can submit a pull request if you’re open to suggestions.)

<img width="1207" alt="Screen Shot 2020-09-29 at 12 01 20 PM" src="https://user-images.githubusercontent.com/154676/94584283-71814780-024c-11eb-9bae-ff7d25f9ed1f.png">

**Comment by GwynethLlewelyn** [comment]
Ugh, yes, that looks ugly in Markdown... maybe using the background colour as the text colour would make more sense? What do you think?

**Comment by skurfer** [comment]
Part of the problem is that Nova doesn’t carry the background color across the whole line, but I think your suggestion would be a huge improvement. (Personally, I would try blue or gray or purple text, but I’m not a fan of yellows and oranges so take that with a grain of salt.) Thanks.

**Comment by GwynethLlewelyn** [comment]
_Finally_ got around to fix this annoying issue. My apologies for taking an eternity to do so!
