### ISSUE TITLE
Adding "advancedPHP" to your Theme

### ISSUE THREAD

**Issue by dennisosaj** [GwynethLlewelyn/Nord.novaextension#2]
Heyho,
I saw your theme and noticed a growing popularity.

I'm asking if you could add "advancedPHP" to your theme. It's one of my own extensions and I want to provide more theme coverage for my users.

You can find a theme development documentation in its repo: https://github.com/dennisosaj/advancedphp.novaextension

I would really appreciate it. Thanks!

**Comment by GwynethLlewelyn** [comment]
Hi there @dennisosaj ! You know, I'm a user of `advancedPHP` as well, and so, naturally, I took a peek at your 'extended syntax' for highlighting — and I _did_ consider to add support for it as well, but, alas, other things took precedence... I guess that your message is my excuse to get back to work, 🤣 

Thanks for the heads-up!

**Comment by GwynethLlewelyn** [comment]
Done 😄 You can try it out... I have compared it with what is produced by the 'standard' PHP-HTML extension, and, as far as I could test it, it works... feel free to report any issues...

Cheers, and thanks again!

**Comment by dennisosaj** [comment]
Hi, I didn't got a notification in my mailbox so I was randomly checking my open issues and saw that you already closed it ^^ I took a look into it and it looks beautiful <3

I will add it to the supported theme list in my next update. Thanks a lot!
